const nodemailer = require('nodemailer');
require('dotenv').config();

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

exports.sendAffirmationEmail = async (to, affirmations) => {
  const mailOptions = {
    from: `"AI Affirmation Mirror" <${process.env.EMAIL_USER}>`,
    to,
    subject: '🌞 Your Daily AI Affirmation',
    html: `
      <h3>✨ Today’s Affirmations</h3>
      <p>${affirmations.replace(/\n/g, '<br>')}</p>
      <hr />
      <small>This email was generated by AI. Stay kind to yourself ❤️</small>
    `,
  };

  return transporter.sendMail(mailOptions);
};
